language: php
php:
  - '7.0'

before_script:
  - export PATH="$PATH:$HOME/.composer/vendor/bin"
  - composer global require "squizlabs/php_codesniffer"

script:
  - phpcs --extensions=php --standard=psr2 .

notifications:
  email:
    on_failure: always
